### ISSUE TITLE
Tenter de forcer le déplacement d'une partie

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#233]
**Comment reproduire ?**
- Créé un contenu avec une partie et une seule
- Cliquer sur le bouton "déplacer" et dans la modale, ne rien sélectionner et cliquer sur le bouton "déplacer". Y'a une erreur `MultiValueDictKeyError at /contenus/deplacer/ "'moving_method'"`

**Comment by artragis** [comment]
Tu peux me donner la stacktrace complète stp?

**Comment by pierre-24** [comment]
```
[15/Aug/2015 11:02:26] "POST /contenus/deplacer/ HTTP/1.1" 500 166717
Internal Server Error: /contenus/deplacer/
Traceback (most recent call last):
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/pbeaujea/Devels/zds-site/zds/member/decorator.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/views/generic/edit.py", line 173, in post
    return self.form_valid(form)
  File "/home/pbeaujea/Devels/zds-site/zds/tutorialv2/views/views_contents.py", line 1554, in form_valid
    if form.data['moving_method'] == MoveElementForm.MOVE_UP:
  File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'moving_method'"
[15/Aug/2015 11:05:02] "POST /contenus/deplacer/ HTTP/1.1" 500 166717
```

**Comment by artragis** [comment]
corrigé
