### ISSUE TITLE
migration : les béta bloquent la mise en place du module

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#26]
# Problème

l'exécution de la commande `python migrate.py` donne (depuis le passage à django 1.7) ceci : 

``` bash
Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/home/fdambrine/pause_midi/zds-site/zds-env/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'forum.Post'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
```
# Solution retenu :

on change la manière de faire les béta pour plutôt faire une clef étrangère depuis PublishableContent vers forum et non le contraire !

**Comment by pierre-24** [comment]
On est bon ici aussi, de facto :)
