### ISSUE TITLE
Encodage

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#75]
Comme je suis en train de le découvrir avec bonheur [ici](https://github.com/zestedesavoir/zds-site/pull/2585/files#r29338922), l'encodage des chaines de caractères est absolument chaotique:
- `get_blob()` renvois du "bytes", qu'on converti en général en utf-8 (sauf quand on oublie)
- `emarkdown()` renvois de l'ascii, sauf quand il y a une erreur dans le code markdown, alors là c'est de l'utf-8. Et pour en rajouter une couche, lui, il ne prend **QUE** de l'unicode en entrée (ça, c'est le coup de grâce pour rendre fou tout le monde)
- `write()`, en python 2, ne veux pas de bytes. Ça le dérange pas d'avoir de l'utf-8 ou de l'ascii, mais surtout pas de bytes.

Une partie du problème provient de python 2 lui-même. L'autre partie du problème provient de comportement proprement démoniaque de la fonction `emarkdown()`. 

Bref! Faire des `catch` de `UnicodeError` et de `UnicodeEncoreError` là ou il y a des `write()` et `emarkdown()` me semble nécessaire d'une part. D'autre part, la bonne idée serait de s'assurer que `get_blob()` renvois bien de l'UTF-8 et pas de l'unicode, sauf que ça peut (!) poser problème ailleurs.

**Comment by pierre-24** [comment]
Logiquement, c'est bon.

Vous pouvez tester comme suis:
- Rétrogradez votre version de markdown (`pip install --upgrade https://github.com/zestedesavoir/Python-ZMarkdown/archive/2.6.0-zds.5.zip`) 
- Créez un article avec pour introduction, conclusion et extrait le code suivant:

```
Cette image va planter: ![](http://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Latin_alphabet_Ćć.svg/langfr-260px-Latin_alphabet_Ćć.svg.png)

Puis ce lien va planter, aussi : [ce lien va rater](http://fr.wikipedia.org/wiki/Clémentine) 
```
- Vérifiez que markdown est pas content
- Validez l'article et vérifiez que vous en êtes empêché.
- **(important)** Prenez un article/tuto déjà validé et modifiez le pour mettre le code  précédemment donné. Validez et vérifiez que vous êtes emêché. Vérifiez également la version déjà publié n'est pas impactée par votre validation ratée ! (_feature_ spécial MOOC d'@Eskimon !)
- Remetez à jour votre markdown (`pip install --upgrade https://github.com/zestedesavoir/Python-ZMarkdown/archive/2.6.0-zds.7.zip`) et constater que tout ce passe alors très bien.

**Comment by artragis** [comment]
J'ai réussi à publier le tuto d'eskimon sur mon site, par contre il y a eu des problèmes dans la génération pandoc.

``` console
[21/Jun/2015 11:23:14] "POST /validations/accepter/185/ HTTP/1.0" 302 0
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[21/Jun/2015 11:23:14] "POST /validations/accepter/185/ HTTP/1.0" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 36338)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 129, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

et le log pandoc

``` console
pandoc: Error producing PDF from TeX source
pandoc: Could not parse YAML header: did not find expected whitespace or line break "source" (line 9243, column 4)
pandoc: Could not parse YAML header: did not find expected whitespace or line break "source" (line 9243, column 4)
pandoc: Could not parse YAML header: did not find expected whitespace or line break "source" (line 9243, column 4)
!(http ://www.dailymotion.com/video/x2kgzr9_initiation-a-

Underfull \hbox (badness 10000) in paragraph at lines 6053--6054
[] []|\EU1/lmss/bx/n/12 4.6.1.0.0.2 Vidéo 2/3[] \EU1/Merriweather(0)/m/sc/12 ->
!(http ://www.dailymotion.com/video/x2kgzrw_initiation-a-

Underfull \hbox (badness 10000) in paragraph at lines 6057--6058
[] []|\EU1/lmss/bx/n/12 4.6.1.0.0.3 Vidéo 3/3[] \EU1/Merriweather(0)/m/sc/12 ->
!(http ://www.dailymotion.com/video/x2kgzse_initiation-a-
[116] [117] <use  "images/f6f165d7-768a-4bec-9deb-9dca19f0677d.png" > [118]

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `math shift' on input line 6264.


Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `subscript' on input line 6264.


Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `math shift' on input line 6264.

[119] <use  "images/2ba4daf9-ec74-400e-9e04-3041c548dc79.png" >
<use  "images/50aa8b9c-ecc4-4bf2-8878-27377d45b37e.png" > [120] [121] [122]
Chapitre 5.
<use  "images/f48e1e1e-343b-4a91-8ba7-6ee67a0738e7.png" >
<use  "images/0291e6c5-afe8-480c-ae6d-42c056b93833.png.960x960_q85.jpg" >
Underfull \hbox (badness 1314) in paragraph at lines 6389--6396
[]\EU1/Merriweather(0)/m/sc/12 Notre ‘charge’ (bobine$[][][]$, relais, moteur…)
 est montée entre la source d’alimentation et le
[123] [124]
<use  "images/8051839e-bc41-406d-855f-9f1513d45c67.png.960x960_q85.jpg" >
[125]

Package hyperref Warning: Difference (2) between bookmark levels is greater
(hyperref)                than one, level fixed on input line 6457.

[126]
Chapitre 6.
[127] <use  "images/a965c354-3f00-47ff-8ece-1247836885c1.png" >
<use  "images/3d6179bc-a1bf-4c95-80ef-174d1417370e.png" > [128] [129] [130]
[131]
Underfull \vbox (badness 10000) has occurred while \output is active [132]
[133] [134]
Underfull \hbox (badness 10000) in paragraph at lines 6942--6943
[]\EU1/Merriweather(0)/m/sc/12 ->!(http ://www.dailymotion.com/video/x2kgzzn_pa
sser-d-un-modele-3d-a-du-langage-
[135] [136]
Chapitre 7.
[137] [138]
<use  "images/e5a28905-77ca-42aa-a371-2bbb4b02fb96.jpg.960x960_q85.jpg" >
[139] [140] [141] <use  "images/5343b937-8d7f-4449-9b25-15cdb9844e03.png" >
[142] [143]
Underfull \vbox (badness 10000) has occurred while \output is active [144]
Underfull \vbox (badness 10000) has occurred while \output is active [145]
<use  "images/717aa5d9-e260-4006-a230-15abfee04196.png.960x960_q85.jpg" >
<use  "images/18ef12bd-f332-4de6-8bff-fca1f1842dd6.png.960x960_q85.jpg" >
[146] [147] <use  "images/7fcc1721-9e56-43d0-a7fd-f04a20d5fdb5.png" >
<use  "images/9fd3ca96-71f7-473a-969b-a5c5c3cc9cfc.png" > [148]
Underfull \hbox (badness 10000) in paragraph at lines 7624--7626


Overfull \hbox (143.0709pt too wide) in paragraph at lines 7638--7639
[] []|\EU1/lmss/bx/n/12 7.8.1.0.0.2 La fraiseuse numérique en 3 parties par Dim
itri[] \EU1/Merriweather(0)/m/sc/12 ->!(https ://www.youtube.com/watch?v=81QJWw
qnRjY)<-

Underfull \hbox (badness 10000) in paragraph at lines 7638--7639

[149] [150]
Chapitre 8.
<use  "images/b5a29172-6ba4-4b63-96c2-bdac38a2ef3f.png" > [151]
<use  "images/8bc5ffbc-9f84-4d98-9a64-a88f0a98a83b.png" > [152]
<use  "images/a0fe06db-b047-46c5-9c7d-c06ba7ca81db.png" >
<use  "images/b5916027-5ea7-41af-b2d1-c74178a7720a.png" >
<use  "images/bd48f4ac-c2d7-4ae3-af1e-563db588084f.png" > [153]
<use  "images/86959da9-c9b5-48df-b9e8-ded514e12af1.png" > [154] [155]
Underfull \hbox (badness 5817) in paragraph at lines 7924--7927
[]\EU1/Merriweather(0)/m/sc/12 [[secret]] | \EU1/AndaleMono(0)/bx/n/12 cpp | /*
 | Démonstration des dialogues I²C avec une DS1307 RTC |

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | N'oubliez pas les deux résistances "pull-up" si la
 platine | 'breakout'

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 n'est pas équipé. | | Glenn Smith mai 2014 | MOOC Fa
brication Numérique |

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 */ | #include <stdarg.h> // pour le fonction "format
" | #include <Wire.h>

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 // Pour le I²C | | /* L'adresse de chaque périperiqu
e est documenté dans

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 sa fiche technique */ | #define addr_ds1307 0x68 //
Adresse du DS1307 sur

Overfull \hbox (10.64436pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 bus I²C | | /* Tableaux de conversion des jours */ |
 const char jours[7][10]

Overfull \hbox (19.79506pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 = { | "Dimanche", | "Lundi", | "Mardi", | "Mercredi"
, | "Jeudi", | "Vendredi",

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | "Samedi" | }; | | /* Tableaux de conversion des mo
is */ | const char

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 mois[12][10] = { | "janvier", | "fevrier", | "mars",
 | "avril", | "mai",

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | "juin", | "juillet", | "aout", | "septembre", | "o
ctobre", | "novembre",

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | "decembre" | }; | | /* | Vous pouvez corrigé les v
aleurs ici pour regler

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 date et heure | */ | // Secs, Mins, Hrs, Jour, Date,
 Mois, (Année - 2000)

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | byte time[7] = {0, 0, 13, 1, 25, 5, 14}; | | char
tempString[32]; //

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 pour le message formaté | | void format(char *fmt, .
.. ){ | va_list args;

Overfull \hbox (44.19577pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | va_start (args, fmt ); // allocation d'espace en m
émoire | vsnprintf(tempString,

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 32, fmt, args); // formattage du message dans tempSt
ring | va_end (args);

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 // liberation des ressources. | } | | /* Conversion
d'une valeur BCD en

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 décimale */ | static uint8_t bcd2bin (uint8_t val) {
 | return val - 6 *

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 (val >> 4); | } | | /* Conversion d'une valeur décim
ale en BCD */ | static

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 uint8_t bin2bcd (uint8_t val) { | return val + 6 * (
val / 10); | } | |

Overfull \hbox (118.31259pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 void start_timer() { | // Configurer la sortie pour
1Hz | Wire.beginTransmission(addr_ds1307);

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | Wire.write(0x07); // addresse du registre | Wire.w
rite(0x10); // Byte

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 to write | Wire.endTransmission(); | // Effacer le c
ontenu du registre 0.

Overfull \hbox (33.21527pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 Ceci pour but de | // démarrer l'horloge. | Wire.beg
inTransmission(addr_ds1307);

Overfull \hbox (4.54422pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | Wire.write(0); // addresse du registre | Wire.writ
e(0); // octet à écrire

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | Wire.endTransmission(); | } | | void regler_horlog
e(byte newtime[7]){

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | byte i; | | Wire.beginTransmission(addr_ds1307); |
 Wire.write(0); //

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 addresse du registre de départ | for (i=0; i<7; i++)
 { // envoyer les 7

Overfull \hbox (27.1151pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 octets un-a-un | Wire.write(bin2bcd(newtime[i])); |
} | Wire.endTransmission();

Overfull \hbox (33.21523pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | } | | void lire_horloge() { | byte i; | | Wire.beg
inTransmission(addr_ds1307);

Overfull \hbox (2.71448pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | Wire.write(0); // adresse du registre de départ |
Wire.endTransmission();

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | // Demande mode lecture, 7 octets | Wire.requestFr
om(addr_ds1307, 7); |

Overfull \hbox (87.50677pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 // lire les octets dans l'ordre | for (i=0; i<7; i++
) { | time[i] = bcd2bin(Wire.read());

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 | } | Wire.endTransmission(); | } | | // Afficher da
te et heure sur la

Overfull \hbox (2.71445pt too wide) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 liaison série | void afficher_lheure () { | Serial.p
rint(jours[time[3]-1]);

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 // le jour | Serial.print(" "); | Serial.print(time[
4]); // la date du

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 mois | Serial.print(" "); | Serial.print(mois[time[5
]-1]); // le mois |

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 Serial.print(" "); | Serial.print(time[6]+2000); //
l'année | format("

Underfull \hbox (badness 10000) in paragraph at lines 7924--7927
\EU1/AndaleMono(0)/bx/n/12 %02u:%02u:%02u", time[2], time[1], time[0]); | Seria
l.println(tempString);

pandoc: Error producing PDF from TeX source
```

**Comment by pierre-24** [comment]
Ça part mal, y'a aucun code maison (_broken pipe_ ?). 

Par contre ... Est ce la bonne issue ? (c'pas une erreur d'encodage)

**Comment by artragis** [comment]
En fait c'est en faisant la QA de cette issue que j'ai eu ça, c'est pour ça.

**Comment by pierre-24** [comment]
Ah, ok ^^

Mais c'est définitivement pas une erreur d'encodage. D'ailleurs, à priori, je vois pas d'erreur TeX non plus o_O

**Comment by artragis** [comment]
tu peux la poster sur le fofo, j'ai pas le temps là.

**Comment by Eskimon** [comment]
On est comment ici ? Ca c'est reproduit ?

**Comment by pierre-24** [comment]
Moi, en local, j'ai ...

```
pandoc: Error producing PDF from TeX source.
! Missing $ inserted.
<inserted text> 
                $
l.10880 ...istance combinée est de \$ 10 k \Omega
```

Ce qui est une erreur qui me dit beaucoup plus quelque chose, et à l'époque, c'était là qu'on avait abandonné. Je peux regarder ce qui se passe à cette ligne là si tu veux ;)

**Comment by Eskimon** [comment]
Facile, il suffit de virer les espaces avant/apres dans la formule pour coller les dollars avec le premier/dernier caracteres. Je l'ai fait ce matin sur mon tuto Arduino et ca marche.

**Comment by pierre-24** [comment]
@Eskimon : la dernière version en date est déjà publiée ?

**Comment by pierre-24** [comment]
(et sinon, y'aurais moyen de chopper l'archive ?)

**Comment by Eskimon** [comment]
C'est publiée en beta oui. Sinon j'ai file l'archive a artragis, mais j'ai pas le lien sous la main la...

**Comment by pierre-24** [comment]
À noter que ma dernière PR (#177) tacklait bien comme il faut l'encodage aussi :p

**Comment by artragis** [comment]
ça n'a jamais pété et on a toujours eu des bons retours, je ferme.
